#!/usr/bin/env python3
"""Regenerate crates/codegen/xai-grok-agent/src/prompt/prompt_encrypted.rs.

The agent ships its three prompt templates XOR-obfuscated so a grep of an
installed binary does not read like a prompt dump; this script re-derives the
encrypted byte blobs from the current template sources after any edit to:

    crates/codegen/xai-grok-agent/templates/prompt.md            -> BASE_PROMPT_ENC
    crates/codegen/xai-grok-agent/templates/apply_patch_prompt.md -> CODEX_PROMPT_ENC
    crates/codegen/xai-grok-agent/templates/subagent_prompt.md    -> SUBAGENT_PROMPT_ENC

Encryption matches template.rs's test helper exactly:
    enc[i] = plain[i] ^ seed.wrapping_add(i as u8)
Run this whenever a template changes; the staleness test fails otherwise.
"""

from __future__ import annotations

import pathlib

CRATE = pathlib.Path(__file__).resolve().parent.parent / "crates" / "codegen" / "xai-grok-agent"
TEMPLATES = CRATE / "templates"
OUT = CRATE / "src" / "prompt" / "prompt_encrypted.rs"

SEEDS = [0x5A, 0x7B, 0x3D]
ENTRIES = [
    ("BASE_PROMPT_ENC", TEMPLATES / "prompt.md", SEEDS[0]),
    ("CODEX_PROMPT_ENC", TEMPLATES / "apply_patch_prompt.md", SEEDS[1]),
    ("SUBAGENT_PROMPT_ENC", TEMPLATES / "subagent_prompt.md", SEEDS[2]),
]


def encrypt(data: bytes, seed: int) -> list[int]:
    return [b ^ ((seed + i) & 0xFF) for i, b in enumerate(data)]


def render(name: str, blob: list[int]) -> str:
    parts = [str(b) for b in blob]
    lines: list[str] = []
    current: list[str] = []
    width = 0
    for part in parts:
        if current and width + len(part) > 100:
            lines.append(",\n".join([]) + ", ".join(current) + ",")
            current = []
            width = 0
        current.append(part)
        width += len(part) + 2
    if current:
        lines.append(", ".join(current))
    body = "\n".join(lines)
    return f"#[rustfmt::skip]\npub(crate) const {name}: &[u8] = &[{body}];\n"


def main() -> None:
    parts = [
        "// Generated by scripts/encrypt_templates.py - do not edit by hand.",
        "// Regenerate whenever the corresponding templates/*.md changes.",
        "",
    ]
    for name, path, seed in ENTRIES:
        blob = encrypt(path.read_bytes(), seed)
        parts.append(render(name, blob))
        parts.append("")
    parts.append(f"pub(crate) const PROMPT_SEEDS: [u8; {len(SEEDS)}] = "
                 + "[" + ", ".join(f"0x{s:02X}" for s in SEEDS) + "];")
    parts.append("")
    OUT.write_text("\n".join(parts), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
